name: main
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Variables
      id: variables
      run: echo ::set-output name=version::$(git describe --tags --always)
    - name: Runtime
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration release
    - name: Move
      run: mv Jellyfin.Plugin.Intros/bin/*/*/Jellyfin.Plugin.Intros.dll .
    - name: Compress
      env:
        version: ${{ steps.variables.outputs.version }}
      run: zip jellyfin-plugin-intros-${version}.zip *.dll
    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      uses: ncipollo/release-action@v1
      with:
        artifacts: '*.zip'
        tag: ${{ steps.variables.outputs.version }}
        commit: ${{ github.ref }}
        token: ${{ github.token }}
